### ISSUE TITLE
'seed' command does not wipe documents from collection before populating

### ISSUE THREAD

**Issue by nmalacarne** [toymachiner62/node-mongo-seeds#12] opened 2015-02-19 22:24 UTC
When I run the 'seed' command, the collection is populated, but the collection is not cleared beforehand.

MongoDB: v2.4.9
NodeJS: v0.12.0

![Screenshot](http://i.imgur.com/IKP1wYh.png)

**Comment by toymachiner62** [comment] 2015-02-20 00:00
Intersting. It should. Thanks for the screenshot btw. So if you run the seed command multiple times your users collection just keeps growing and growing?

What version of node-mongo-seeds are you using?

**Comment by nmalacarne** [comment] 2015-02-20 14:45
Sorry, I should have been more specific with the original post. The screenshot was taken after the second 'seed' command. Each additional 'seed' adds a new document to the users collection without first wiping all the existing documents.

I am using node-mongo-seeds v2.2.4 on NodeJS v0.12.0. I tried dropping down to NodeJS v0.11.14 and then v0.10.33, but I am having the same problem on those versions as well.

I may dig deeper sometime this weekend, but for now I will just have to clear it manually before seeding; the seeding works fine and helps out a lot, so thanks for the package. ;)

**Comment by toymachiner62** [comment] 2015-02-20 14:56
Interesting. I've not seen this behavior before and i'm using this package in a couple projects. I'll see if i can dig into it a bit though.

**Comment by toymachiner62** [comment] 2015-02-20 15:52
Do you by chance have a separate user setup that does not have drop collection permissions?

Here's the lines of code that drop the collection before adding it. https://github.com/toymachiner62/node-mongo-seeds/blob/v2.2.4/lib/seed.js#L112-L120

Here's the drop collection method itself: https://github.com/toymachiner62/node-mongo-seeds/blob/v2.2.4/lib/seed.js#L203-L226

**Comment by toymachiner62** [comment] 2015-02-24 19:29
I actually just came across this same issue myself. It does not happen to me locally but happens when I run it on my server. I'll have to investigate

**Comment by nmalacarne** [comment] 2015-02-25 14:39
Thanks for the update. I cloned this project to another computer with the same OS (ubuntu 14.04), ran the tests, and everything passed. I still had the problem with it not wiping a collection before seeding though.

As for the user setup... I am running node with mongo out of the box. I do not remember doing anything with user setups, but this is my first time using mongo so it is possible that I haven't set it up fully.

**Comment by rhinko** [comment] 2015-03-25 19:24
There seems to be issue with 'collectionExist' function. It appears that collection name is not pre-pended by database name anymore and when testing if collection exists you only need to pass name.
Line 247 needs to be changed to
```javascript
      if(_.findWhere(collections, {name: name})) {
```
from
```javascript
      if(_.findWhere(collections, {name: (db.databaseName + '.' + name)})) {
```

**Comment by anshupitlia** [comment] 2015-04-16 12:45
I am also having this issue. Has some workaround been found?

**Comment by toymachiner62** [comment] 2015-04-16 12:51
The only workaround right now is to manually delete your database and then run the seed command again.

**Comment by TheJKFever** [comment] 2015-04-30 07:33
I am also having this issue. Let me know if you have any questions about my setup, etc.

**Comment by toymachiner62** [comment] 2015-05-01 14:39
@TheJKFever What OS are you having this issue on? So far i've only heard reports (including myself) on  this issue on Ubuntu.

**Comment by seanemmer** [comment] 2015-06-01 23:57
also running into this issue on OSX

**Comment by toymachiner62** [comment] 2015-06-03 01:57
@rhinko the latest version which is 2.2.4 has the code that you suggested here https://github.com/toymachiner62/node-mongo-seeds/issues/12#issuecomment-86181437

@seanemmer can you provide details of your setup? What version of node-mongo-seeds are you using? Are you using it globally? Can you provide a simple reproducible project that I can take a look at?

**Comment by seanemmer** [comment] 2015-06-03 03:31
@toymachiner62 I was using latest version of node-mongo-seeds, set globally.  I was running off of the MEAN stack (mongo, express, angular, node).  I ended up building out a slightly different implementation that supports mongoose validation and non-string db values:

[https://www.npmjs.com/package/mongoose-seed](https://www.npmjs.com/package/mongoose-seed)

**Comment by emadb** [comment] 2015-06-10 09:55
@toymachiner62 did you see my PR? Please check if it is ok and merge it. We are using your package in one of our project and we need that fix. Don't force me to fork :-) Thx

**Comment by toymachiner62** [comment] 2015-06-10 13:23
I've merged @emadb's pull request which should fix this issue. I'm closing assuming it's fixed for everyone. Let me know if it's not fixed for you.

**Closed by toymachiner62** 2015-06-10 13:23 UTC
Labels: bug, help wanted
